name: ms-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pyyaml
  - tqdm
  - pip
  - pip:
    - rank-bm25
    - sentence-transformers
    - faiss-cpu
    - rouge-score
